CREATE TABLE `PRODUCT` (
	`PNO`	PK	NOT NULL,
	`CNO`	PK	NOT NULL,
	`PNAME`	NOT NULL	NULL,
	`PPRICE`	NOT NULL	NULL,
	`PINFO`	NOT NULL	NULL,
	`FPREC`	NOT NULL	NULL,
	`PENROLL`	SYSDATE	NULL,
	`PSTOCK`	NOT NULL	NULL,
	`PSELL`	VARCHAR(255)	NULL
);

CREATE TABLE `CART` (
	`CARTNO`	PK	NOT NULL,
	`CARTUSERID`	FK	NULL,
	`PNO`	FK	NOT NULL,
	`AMOUNT`	NOT NULL	NULL,
	`PNAME`	FK	NULL,
	`PPRICE`	FK	NULL,
	`ORDERPRICE`	NOT NULL	NULL
);

CREATE TABLE `MEMBER` (
	`USERID`	PK	NULL,
	`LEVELTYPE`	FK	NOT NULL,
	`PASSWORD`	NOT NULL	NULL,
	`USERNAME`	NOT NULL	NULL,
	`BIRTH`	NOT NULL	NULL,
	`GENDER`	NOT NULL	NULL,
	`EMAIL`	NOT NULL	NULL,
	`PHONE`	NOT NULL	NULL,
	`ADDRESS`	NOT NULL	NULL,
	`ENROLL_DATE`	SYSDATE	NULL,
	`STATUS`	NOT NULL, DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL,
	`MEMO`	VARCHAR(255)	NULL
);

CREATE TABLE `ORDERED` (
	`ORDERID`	PK	NOT NULL,
	`STATUSNO`	PK	NOT NULL,
	`ORDERUSERID`	FK	NOT NULL,
	`TOTALPRICE`	NOTNULL	NULL,
	`ORDERENROLL`	SYSDATE	NULL,
	`CUSTOMERNAME`	NOT NULL	NULL,
	`RECEIVERNAME`	NOT NULL	NULL,
	`ADDRESS1`	NOT NULL	NULL,
	`ADDRESS2`	NOT NULL	NULL,
	`PHONE`	NOT NULL	NULL,
	`FEE`	NOT NULL	NULL
);

CREATE TABLE `REVIEW` (
	`RENO`	PK	NOT NULL,
	`PNO`	FK	NOT NULL,
	`REUSERID`	FK	NULL,
	`RETITLE`	NOT NULL	NULL,
	`RECONTENT`	NOTNULL	NULL,
	`REUPLOADDATE`	SYSDATE	NULL,
	`STATUS`	NOT NULL, DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL
);

CREATE TABLE `PATTACHMENT` (
	`PANO`	PK	NOT NULL,
	`PNO`	FK	NOT NULL,
	`ORIGINALNAME`	NOT NULL	NULL,
	`CHANGENAME`	NOT NULL	NULL,
	`UPLOADDATE`	SYSDATE	NULL,
	`STATUS`	NOT NULL, DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL
);

CREATE TABLE `CATEGORY` (
	`CNO`	PK	NOT NULL,
	`CNAME`	NOT NULL	NULL
);

CREATE TABLE `USERLEVEL` (
	`LEVELTYPE`	PK	NOT NULL,
	`LEVELNAME`	NOT NULL, DEFAULT '1' , 1 - 일반회원 2 - 관리자	NULL
);

CREATE TABLE `SURVEY` (
	`USERID`	PK	NOT NULL,
	`USERNAME`	NOT NULL	NULL,
	`BIRTH`	SYSDATE	NULL,
	`GENDER`	NOT NULL	NULL,
	`ANSWERTYPE`	NOT NULL	NULL,
	`RESULT`	VARCHAR(255)	NULL
);

CREATE TABLE `QNA` (
	`QANO`	PK	NOT NULL,
	`QAUSERID`	FK	NULL,
	`QATITLE`	NOT NULL	NULL,
	`QACONTENET`	NOTNULL	NULL,
	`QAUPLOADDATE`	SYSDATE	NULL,
	`STATUS`	NOT NULL, DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL,
	`QASEL`	VARCHAR(255)	NULL
);

CREATE TABLE `QNARe` (
	`RNO`	PK	NOT NULL,
	`QANO`	FK	NOT NULL,
	`QAUSERID`	FK	NULL,
	`RTITLE`	NOT NULL	NULL,
	`RCONTENET`	NOTNULL	NULL,
	`RDATE`	SYSDATE	NULL
);

CREATE TABLE `RATTACHMENT` (
	`RANO`	PK	NOT NULL,
	`RENO`	FK	NOT NULL,
	`ORIGINALNAME`	NOT NULL	NULL,
	`CHANGENAME`	NOT NULL	NULL,
	`UPLOADDATE`	SYSDATE	NULL,
	`STATUS`	NOT NULL, DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL
);

CREATE TABLE `DELIVERY` (
	`STATUSNO`	PK	NOT NULL,
	`STATUS`	NOT NULL, DEFAULT '1 ' - 1 배송준비중 2 배송중 3 배송완료	NULL
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`PNO`,
	`CNO`
);

ALTER TABLE `CART` ADD CONSTRAINT `PK_CART` PRIMARY KEY (
	`CARTNO`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`USERID`,
	`LEVELTYPE`
);

ALTER TABLE `ORDERED` ADD CONSTRAINT `PK_ORDERED` PRIMARY KEY (
	`ORDERID`,
	`STATUSNO`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`RENO`
);

ALTER TABLE `PATTACHMENT` ADD CONSTRAINT `PK_PATTACHMENT` PRIMARY KEY (
	`PANO`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CNO`
);

ALTER TABLE `USERLEVEL` ADD CONSTRAINT `PK_USERLEVEL` PRIMARY KEY (
	`LEVELTYPE`
);

ALTER TABLE `SURVEY` ADD CONSTRAINT `PK_SURVEY` PRIMARY KEY (
	`USERID`
);

ALTER TABLE `QNA` ADD CONSTRAINT `PK_QNA` PRIMARY KEY (
	`QANO`
);

ALTER TABLE `QNARe` ADD CONSTRAINT `PK_QNARE` PRIMARY KEY (
	`RNO`
);

ALTER TABLE `RATTACHMENT` ADD CONSTRAINT `PK_RATTACHMENT` PRIMARY KEY (
	`RANO`
);

ALTER TABLE `DELIVERY` ADD CONSTRAINT `PK_DELIVERY` PRIMARY KEY (
	`STATUSNO`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `FK_CATEGORY_TO_PRODUCT_1` FOREIGN KEY (
	`CNO`
)
REFERENCES `CATEGORY` (
	`CNO`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_USERLEVEL_TO_MEMBER_1` FOREIGN KEY (
	`LEVELTYPE`
)
REFERENCES `USERLEVEL` (
	`LEVELTYPE`
);

ALTER TABLE `ORDERED` ADD CONSTRAINT `FK_DELIVERY_TO_ORDERED_1` FOREIGN KEY (
	`STATUSNO`
)
REFERENCES `DELIVERY` (
	`STATUSNO`
);

